<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>DemoTestSuite</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <lastRun>2019-02-26T19:47:51</lastRun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>1</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>true</rerunFailedTestCasesOnly>
   <testSuiteGuid>9cff90a1-bb8b-4fa4-8acd-59981f1d62e1</testSuiteGuid>
   <testCaseLink>
      <guid>d56c7f9e-e1a0-468d-89e4-755df63a648e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Day3/Test4</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b48c33ff-4f1b-4e5f-b553-c3206736b885</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a45c321a-c667-4b5d-b578-c41ad1b098cd</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>f9711de5-228f-4d3f-9c67-535a46921337</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Day3/Test6</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9775533c-150a-4d1a-aa8e-d2f91b187b9a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>399a0536-4cfd-448d-b556-ad00ba21fd7c</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>ad46b107-5c48-464c-91be-5bb8cb3be66b</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Day3/DelayTC</testCaseId>
   </testCaseLink>
</TestSuiteEntity>
