<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>TestSuite3</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>71493809-c478-4008-8b7f-134a696afef3</testSuiteGuid>
   <testCaseLink>
      <guid>03e8c34a-aca3-4638-bbad-56e2af50760d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Day3/Test6</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>26e23f0d-722b-4918-9be8-8de526f87d75</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/data1</testDataId>
      </testDataLink>
      <variableLink>
         <testDataLinkId>26e23f0d-722b-4918-9be8-8de526f87d75</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Username</value>
         <variableId>9775533c-150a-4d1a-aa8e-d2f91b187b9a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>26e23f0d-722b-4918-9be8-8de526f87d75</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Password</value>
         <variableId>399a0536-4cfd-448d-b556-ad00ba21fd7c</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
